  const API = window.VAEL_API_BASE || '';

  // ── i18n ──────────────────────────────────────────────────────────────
  const STRINGS = {
    tagline: 'Vulnerability Analysis Engine',
      analyzeTitle: 'Analyze Software',
      demoLabel: 'Demo scenarios:',
      swLabel: 'Software / Package Name',
      swPlaceholder: 'e.g. log4j, nginx, openssl',
      verLabel: 'Version',
      verPlaceholder: 'e.g. 2.14.1',
      cpeLabel: 'CPE String (optional)',
      ecosystemLabel: 'Ecosystem (optional)',
      ecosystemPlaceholder: 'e.g. Maven, PyPI, npm',
      optOffline: 'Offline mode (no network)',
      optDeterministic: 'Deterministic verdict (no AI)',
      optSkipGithub: 'Skip GitHub PoC search',
      btnAnalyze: 'Analyze',
      btnClear: 'Clear',
      tabCVE: 'CVE Inventory',
      tabExploit: 'Exploitability',
      tabPoC: 'Public PoCs',
      tabExposure: 'Global Exposure',
      tabAttack: 'Attack Path',
      tabVerdict: 'AI Verdict',
      tabDelta: 'Delta Tracker',
      exposureDesc: 'Query Shodan, Censys, FOFA, and ZoomEye to count globally internet-exposed hosts running the analyzed software. Results are cached for 6 hours.',
      btnCheckExposure: 'Check Global Exposure',
      deltaDesc: 'Compare today\'s analysis against the saved baseline to surface new CVEs, tier escalations, KEV additions, EPSS spikes, and new public exploits. Run repeatedly to track the threat landscape over time.',
      btnRunDelta: 'Run Delta Analysis',
      deltaNoSoftware: 'Run the main analysis first, then return here to compare against the baseline.',
      deltaChecking: 'Checking baseline status…',
      deltaNoBaseline: 'No baseline saved yet — this run will create one.',
      deltaHasBaseline: 'Baseline saved',
      deltaRunning: 'Running delta analysis…',
      deltaNoChanges: 'No changes detected since last baseline.',
      omanTitle: '🇴🇲 Oman Internet Exposure',
      omanPowered: 'Powered by Shodan · FOFA · Censys · ZoomEye',
      omanDesc: 'Search for publicly reachable hosts inside Oman running a given software or exposed to a specific vulnerability. Independent from the main analysis.',
      omanSwLabel: 'Software',
      omanSwPlaceholder: 'e.g. apache, nginx, log4j',
      omanVerLabel: 'Version',
      btnSearchOman: 'Search Oman 🇴🇲',
      btnCopyFromAnalysis: 'Copy from analysis',
      roadmapTitle: '📋 Project Roadmap',
      roadmapCompleted: '✓ Completed',
      roadmapNext: '→ Coming Next',
      roadmapHistory: 'Version History',
      rateLimitTitle: '⚠ Rate limit warnings',
      loadingStage1: 'Stage 1: mapping CVEs from NVD + OSV…',
      loadingStage2: 'Stage 2: fetching EPSS scores + CISA KEV…',
      loadingStage3: 'Stage 3: harvesting PoCs from GitHub, Exploit-DB, Nuclei, Metasploit, Packet Storm, Pastebin + intl…',
      loadingVerdict: 'Generating AI verdict…',
      statTotalCVEs: 'Total CVEs',
      statCritical: 'Critical',
      statHigh: 'High',
      statVerMatch: 'Ver. Match',
      statInKEV: 'In KEV',
      statPatchNow: 'Patch Now',
      statT1High: 'T1 High',
      statMonitor: 'Monitor',
      statPoCs: 'Public PoCs',
      statMisconfig: 'Misconfigs',
      attackDesc: 'Maps discovered CVEs to MITRE ATT&CK tactics using CWE cross-walk and CVSS heuristics. Shows which kill-chain stages are reachable and which techniques an attacker would use.',
      btnMapAttack: 'Map Attack Path',
      attackNoSoftware: 'Run the main analysis first, then map the attack path.',
      attackRunning: 'Building ATT&CK kill-chain…',
      attackEmpty: 'No ATT&CK mappings found — CVEs may lack CWE tags or CVSS vectors.',
      attackStatTactics: 'Tactics Covered',
      attackStatTechniques: 'Techniques',
      attackStatHighestRisk: 'Highest-Risk Tactic',
      attackClickTactic: 'Click a tactic box to see techniques and CVEs.',
      btnDownloadMd: 'Download Report (.md)',
      btnDownloadJson: 'Export JSON',
  };

  function t(key) { return STRINGS[key] || key; }
